CREATE TABLE XY_HTN_GPI_CLASS
(
   GPI_CATEGORY_3   VARCHAR2 (60),
   GPI_CATEGORY_4   VARCHAR2 (60),
   COMBO            VARCHAR2 (60),
   CLASS            VARCHAR2 (15)
)
NOCACHE
LOGGING;


INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIRECT RENIN INHIBITORS ',
             'ALISKIREN-HYDROCHLOROTHIAZIDE',
             'ALISKIREN',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'ALISKIREN-HYDROCHLOROTHIAZIDE',
             'ALISKIREN',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'AMLODIPINE-OLMESARTAN',
             'AMLODIPINE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CA CHANNEL BLOCKER COMB',
             'AMLODIPINE-OLMESARTAN',
             'AMLODIPINE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'AMLODIPINE BESY-BENAZEPRIL HCL',
             'AMLODIPINE BESY',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'AMLODIPINE BESY-BENAZEPRIL HCL',
             'AMLODIPINE BESY',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'AMLODIPINE BESYLATE-VALSARTAN',
             'AMLODIPINE BESYLATE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CA CHANNEL BLOCKER COMB',
             'AMLODIPINE BESYLATE-VALSARTAN',
             'AMLODIPINE BESYLATE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'ATENOLOL-CHLORTHALIDONE',
             'ATENOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'ATENOLOL-CHLORTHALIDONE',
             'ATENOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'BENAZEPRIL-HYDROCHLOROTHIAZIDE',
             'BENAZEPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'BENAZEPRIL-HYDROCHLOROTHIAZIDE',
             'BENAZEPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'AMLODIPINE BESY-BENAZEPRIL HCL',
             'BENAZEPRIL HCL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'AMLODIPINE BESY-BENAZEPRIL HCL',
             'BENAZEPRIL HCL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'NADOLOL-BENDROFLUMETHIAZIDE',
             'BENDROFLUMETHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'NADOLOL-BENDROFLUMETHIAZIDE',
             'BENDROFLUMETHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('RESERPINE COMBINATIONS',
             'BENDROFLUMETHIAZIDE-RAUWOLFIA',
             'BENDROFLUMETHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'BISOPROLOL-HYDROCHLOROTHIAZIDE',
             'BISOPROLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'BISOPROLOL-HYDROCHLOROTHIAZIDE',
             'BISOPROLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'CANDESARTAN CILEXETIL-HCTZ',
             'CANDESARTAN CILEXETIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'CANDESARTAN CILEXETIL-HCTZ',
             'CANDESARTAN CILEXETIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ADRENOLYTICS-CENTRAL ',
             'CLONIDINE-CHLORTHALIDONE',
             'CHLORTHALIDONE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'ATENOLOL-CHLORTHALIDONE',
             'CHLORTHALIDONE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'ATENOLOL-CHLORTHALIDONE',
             'CHLORTHALIDONE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'CLONIDINE-CHLORTHALIDONE',
             'CHLORTHALIDONE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ADRENOLYTICS-CENTRAL ',
             'CLONIDINE-CHLORTHALIDONE',
             'CLONIDINE',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'CLONIDINE-CHLORTHALIDONE',
             'CLONIDINE',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'ENALAPRIL-HYDROCHLOROTHIAZIDE',
             'ENALAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'ENALAPRIL-HYDROCHLOROTHIAZIDE',
             'ENALAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'ENALAPRIL MALEATE-FELODIPINE',
             'ENALAPRIL MALEATE',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'ENALAPRIL MALEATE-FELODIPINE',
             'ENALAPRIL MALEATE',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'EPROSARTAN MESYLATE-HCTZ',
             'EPROSARTAN MESYLATE',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'EPROSARTAN MESYLATE-HCTZ',
             'EPROSARTAN MESYLATE',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'ENALAPRIL MALEATE-FELODIPINE',
             'FELODIPINE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'ENALAPRIL MALEATE-FELODIPINE',
             'FELODIPINE',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'FOSINOPRIL SODIUM-HCTZ',
             'FOSINOPRIL SODIUM',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'FOSINOPRIL SODIUM-HCTZ',
             'FOSINOPRIL SODIUM',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'FOSINOPRIL SODIUM-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'CANDESARTAN CILEXETIL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'EPROSARTAN MESYLATE-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'LOSARTAN POTASSIUM-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'OLMESARTAN MEDOXOMIL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'TELMISARTAN-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'PROPRANOLOL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'PROPRANOLOL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'CANDESARTAN CILEXETIL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'EPROSARTAN MESYLATE-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'FOSINOPRIL SODIUM-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'LOSARTAN POTASSIUM-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'OLMESARTAN MEDOXOMIL-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'TELMISARTAN-HCTZ',
             'HCTZ',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'BENAZEPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'ENALAPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'LISINOPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'QUINAPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ADRENOLYTICS-CENTRAL ',
             'METHYLDOPA-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'VALSARTAN-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'BISOPROLOL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'METOPROLOL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIRECT RENIN INHIBITORS ',
             'ALISKIREN-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'BISOPROLOL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'METOPROLOL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'BENAZEPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'ENALAPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'LISINOPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'QUINAPRIL-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'VALSARTAN-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'ALISKIREN-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'METHYLDOPA-HYDROCHLOROTHIAZIDE',
             'HYDROCHLOROTHIAZIDE',
             'HCTZ');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'LISINOPRIL-HYDROCHLOROTHIAZIDE',
             'LISINOPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'LISINOPRIL-HYDROCHLOROTHIAZIDE',
             'LISINOPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'LOSARTAN POTASSIUM-HCTZ',
             'LOSARTAN POTASSIUM',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'LOSARTAN POTASSIUM-HCTZ',
             'LOSARTAN POTASSIUM',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ADRENOLYTICS-CENTRAL ',
             'METHYLDOPA-HYDROCHLOROTHIAZIDE',
             'METHYLDOPA',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE COMB',
             'METHYLDOPA-HYDROCHLOROTHIAZIDE',
             'METHYLDOPA',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'METOPROLOL-HYDROCHLOROTHIAZIDE',
             'METOPROLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'METOPROLOL-HYDROCHLOROTHIAZIDE',
             'METOPROLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'NADOLOL-BENDROFLUMETHIAZIDE',
             'NADOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'NADOLOL-BENDROFLUMETHIAZIDE',
             'NADOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'AMLODIPINE-OLMESARTAN',
             'OLMESARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CA CHANNEL BLOCKER COMB',
             'AMLODIPINE-OLMESARTAN',
             'OLMESARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'OLMESARTAN MEDOXOMIL-HCTZ',
             'OLMESARTAN MEDOXOMIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'OLMESARTAN MEDOXOMIL-HCTZ',
             'OLMESARTAN MEDOXOMIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('BETA BLOCKER ',
             'PROPRANOLOL-HCTZ',
             'PROPRANOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('DIURETIC COMBINATIONS',
             'PROPRANOLOL-HCTZ',
             'PROPRANOLOL',
             'BB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS ',
             'QUINAPRIL-HYDROCHLOROTHIAZIDE',
             'QUINAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'QUINAPRIL-HYDROCHLOROTHIAZIDE',
             'QUINAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('RESERPINE COMBINATIONS',
             'BENDROFLUMETHIAZIDE-RAUWOLFIA',
             'RAUWOLFIA',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'TELMISARTAN-HCTZ',
             'TELMISARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'TELMISARTAN-HCTZ',
             'TELMISARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'TRANDOLAPRIL-VERAPAMIL HCL',
             'TRANDOLAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'TRANDOLAPRIL-VERAPAMIL HCL',
             'TRANDOLAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'AMLODIPINE BESYLATE-VALSARTAN',
             'VALSARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAG ',
             'VALSARTAN-HYDROCHLOROTHIAZIDE',
             'VALSARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CA CHANNEL BLOCKER COMB',
             'AMLODIPINE BESYLATE-VALSARTAN',
             'VALSARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('THIAZIDE/THIAZIDE-LIKE',
             'VALSARTAN-HYDROCHLOROTHIAZIDE',
             'VALSARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITOR ',
             'TRANDOLAPRIL-VERAPAMIL HCL',
             'VERAPAMIL HCL',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('CALCIUM CHANNEL BLOCKER COMBINATIONS',
             'TRANDOLAPRIL-VERAPAMIL HCL',
             'VERAPAMIL HCL',
             'CCB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'BENAZEPRIL HCL',
             'BENAZEPRIL HCL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'CAPTOPRIL',
             'CAPTOPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'ENALAPRIL MALEATE',
             'ENALAPRIL MALEATE',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'ENALAPRILAT',
             'ENALAPRILAT',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'FOSINOPRIL SODIUM',
             'FOSINOPRIL SODIUM',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'LISINOPRIL',
             'LISINOPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'MOEXIPRIL HCL',
             'MOEXIPRIL HCL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'PERINDOPRIL ERBUMINE',
             'PERINDOPRIL ERBUMINE',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'QUINAPRIL HCL',
             'QUINAPRIL HCL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'RAMIPRIL',
             'RAMIPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ACE INHIBITORS',
             'TRANDOLAPRIL',
             'TRANDOLAPRIL',
             'ACE');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'CANDESARTAN CILEXETIL',
             'CANDESARTAN CILEXETIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'IRBESARTAN',
             'IRBESARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'LOSARTAN POTASSIUM',
             'LOSARTAN POTASSIUM',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'OLMESARTAN MEDOXOMIL',
             'OLMESARTAN MEDOXOMIL',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'TELMISARTAN',
             'TELMISARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANGIOTENSIN II RECEPTOR ANTAGONISTS',
             'VALSARTAN',
             'VALSARTAN',
             'ARB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - CENTRALLY ACTING',
             'CLONIDINE HCL',
             'CLONIDINE HCL',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - CENTRALLY ACTING',
             'GUANABENZ ACETATE',
             'GUANABENZ ACETATE',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - CENTRALLY ACTING',
             'GUANFACINE HCL',
             'GUANFACINE HCL',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - CENTRALLY ACTING',
             'METHYLDOPA',
             'METHYLDOPA',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - PERIPHERALLY ACTING',
             'DOXAZOSIN MESYLATE',
             'DOXAZOSIN MESYLATE',
             'AB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - PERIPHERALLY ACTING',
             'PRAZOSIN HCL',
             'PRAZOSIN HCL',
             'AB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('ANTIADRENERGICS - PERIPHERALLY ACTING',
             'TERAZOSIN HCL',
             'TERAZOSIN HCL',
             'AB');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('RESERPINE',
             'RESERPINE',
             'RESERPINE',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('VASODILATORS',
             'HYDRALAZINE HCL',
             'HYDRALAZINE HCL',
             'OTH');

INSERT INTO XY_GPI_TEMP_CLASS (GPI_CATEGORY_3,
                               GPI_CATEGORY_4,
                               COMBO,
                               CLASS)
     VALUES ('VASODILATORS',
             'MINOXIDIL',
             'MINOXIDIL',
             'OTH');

COMMIT;